// Publisher icons downloaded from Google Play. See assets/subscription-icons/sources.json.
export const SUBSCRIPTION_ICONS: Record<string, number> = {
  'netflix': require('../assets/subscription-icons/netflix.webp'),
  'prime': require('../assets/subscription-icons/prime.webp'),
  'hotstar': require('../assets/subscription-icons/hotstar.webp'),
  'disney': require('../assets/subscription-icons/disney.webp'),
  'zee5': require('../assets/subscription-icons/zee5.webp'),
  'sonyliv': require('../assets/subscription-icons/sonyliv.webp'),
  'jiotv': require('../assets/subscription-icons/jiotv.webp'),
  'mxplayer': require('../assets/subscription-icons/mxplayer.webp'),
  'sunnxt': require('../assets/subscription-icons/sunnxt.webp'),
  'manoramamax': require('../assets/subscription-icons/manoramamax.webp'),
  'sainaplay': require('../assets/subscription-icons/sainaplay.webp'),
  'aha': require('../assets/subscription-icons/aha.webp'),
  'hoichoi': require('../assets/subscription-icons/hoichoi.webp'),
  'eros': require('../assets/subscription-icons/eros.webp'),
  'appletv': require('../assets/subscription-icons/appletv.webp'),
  'crunchyroll': require('../assets/subscription-icons/crunchyroll.webp'),
  'youtube': require('../assets/subscription-icons/youtube.webp'),
  'googletv': require('../assets/subscription-icons/googletv.webp'),
  'ytmusic': require('../assets/subscription-icons/ytmusic.webp'),
  'spotify': require('../assets/subscription-icons/spotify.webp'),
  'jiosaavn': require('../assets/subscription-icons/jiosaavn.webp'),
  'gaana': require('../assets/subscription-icons/gaana.webp'),
  'wynk': require('../assets/subscription-icons/wynk.webp'),
  'audible': require('../assets/subscription-icons/audible.webp'),
  'jio': require('../assets/subscription-icons/jio.webp'),
  'airtel': require('../assets/subscription-icons/airtel.webp'),
  'googleone': require('../assets/subscription-icons/googleone.webp'),
};
