import type { TextStyle } from 'react-native';

export const fontFamilies = {
  heading: 'Poppins_600SemiBold',
  headingBold: 'Poppins_700Bold',
  body: 'Inter_400Regular',
  bodyMedium: 'Inter_500Medium',
  bodySemiBold: 'Inter_600SemiBold',
  mono: 'Courier New',
} as const;

export const typography = {
  h1: {
    fontSize: 28,
    fontWeight: '700',
    fontFamily: fontFamilies.headingBold,
    lineHeight: 36,
    letterSpacing: -0.5,
    color: '#1F2937',
  },
  h2: {
    fontSize: 20,
    fontWeight: '600',
    fontFamily: fontFamilies.heading,
    lineHeight: 28,
    letterSpacing: -0.25,
    color: '#1F2937',
  },
  h3: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: fontFamilies.heading,
    lineHeight: 26,
    color: '#1F2937',
  },
  h4: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: fontFamilies.heading,
    lineHeight: 24,
    color: '#1F2937',
  },
  bodyLarge: {
    fontSize: 16,
    fontWeight: '400',
    fontFamily: fontFamilies.body,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: '#374151',
  },
  bodyRegular: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: fontFamilies.body,
    lineHeight: 21,
    letterSpacing: 0.25,
    color: '#374151',
  },
  bodySmall: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: fontFamilies.body,
    lineHeight: 18,
    color: '#6B7280',
  },
  labelLarge: {
    fontSize: 16,
    fontWeight: '500',
    fontFamily: fontFamilies.bodyMedium,
    lineHeight: 24,
    letterSpacing: 0.5,
    color: '#1F2937',
  },
  labelRegular: {
    fontSize: 14,
    fontWeight: '500',
    fontFamily: fontFamilies.bodyMedium,
    lineHeight: 21,
    letterSpacing: 0.25,
    color: '#1F2937',
  },
  labelSmall: {
    fontSize: 12,
    fontWeight: '500',
    fontFamily: fontFamilies.bodyMedium,
    lineHeight: 18,
    color: '#1F2937',
  },
  caption: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: fontFamilies.body,
    lineHeight: 16,
    color: '#9CA3AF',
  },
  overline: {
    fontSize: 11,
    fontWeight: '600',
    fontFamily: fontFamilies.bodySemiBold,
    lineHeight: 16,
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#6B7280',
  },
  amount: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: fontFamilies.mono,
    lineHeight: 26,
    color: '#1F2937',
  },
  subamount: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: fontFamilies.mono,
    lineHeight: 21,
    color: '#1F2937',
  },
} satisfies Record<string, TextStyle>;
